excluded: # paths to ignore during linting. Takes precedence over `included`.
- Application/Extensions/Designable+.swift
- Repository/NETWORK+ENDPOINTS.swift
- Core/Repository/KenozTrolly/KenozTrollyModel.swift
- Core/Repository/KenozTrolly/GeneralSectionsModel.swift
- Core/Repository/KenozTrolly/KenozTrollySliderModel.swift
- Core/Repository/KenozTrolly/KenozTrollySellersListModel.swift
- Core/Repository/KenozTrolly/PhotoGrapherModel.swift
- Application/Features/KenozTrolly/KenozTrollyViewController.swift
- Application/Features/Seller/SellerViewController.swift
- Core/Repository/KenozMagazine/KenozMagazineModel.swift
- Core/Repository/KenozTrolly/KenozTrollyProductModel.swift
- Core/Repository/News/NewsModel.swift
- Core/Repository/HorseCleats/HorseCleatsModel.swift
- Core/Repository/Events/EventModel.swift
- Core/Repository/Login/LoginModel.swift
- Core/Repository/SignUp/SignUpModel.swift
- Core/Repository/EditAccount/EditAccountModel.swift
- Core/Repository/Favourite/FavouriteModel.swift
- Core/Repository/TheFamous/TheFamousModel.swift
- Core/Repository/CleatsDetails/CleatsDetailsModel.swift
- Core/Repository/Seller/SellerModel.swift
- Core/Repository/PhotosList/PhotosListModel.swift
- Core/Repository/ProductDetails/ProductDetailsModel.swift
- Core/Repository/Cart/CartModel.swift
- Core/Repository/CompleteOrder/CompleteOrderModel.swift
- Core/Repository/Seller/AboutSellerModel.swift
- Core/Repository/Seller/CompanyProductsModel.swift
- Core/Repository/Sections/SectionsModel.swift
- Core/Repository/ProductList/ProductListModel.swift
- Core/Repository/MyOrdersList/MyOrdersListModel.swift
- Core/Repository/MyOrdersDetails/MyOrdersDetailsModel.swift
- Core/Repository/AboutApplication/ConfigModel.swift
- Core/Repository/Champions/ChampionsModel.swift
- Core/Repository/CompanyList/CompanyListModel.swift
- Pods
- node_modules
- R.generated.swift
